version: '3.7'

services:
  app:
    container_name: rust-tutorial
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 7010:7010
    volumes:
      - ./:/app
    working_dir: /app/src
    command: /bin/sh -c "cargo watch -x run"
